### ISSUE TITLE
New releases?

### ISSUE THREAD

**Issue by LobsterUberlord** [sipsorcery-org/SIPSorceryMedia.FFmpeg#15]
The latest version of this package available on NuGet is `0.0.10-pre`, which was published over a year ago. Are there any plans to publish a new version soon?

**Comment by sipsorcery** [comment]
https://www.nuget.org/packages/SIPSorceryMedia.FFmpeg/0.0.12-pre

**Comment by ChristopheI** [comment]
I will close the issue, as it seems solved. (v1.0.0 and v1.1.0 were released in meantime)

Feel free to ask any other question, or reopen issue.
