### ISSUE TITLE
FFmpegAudioEndPoint

### ISSUE THREAD

**Issue by salihy** [sipsorcery-org/SIPSorceryMedia.FFmpeg#3]
Hi, is there a way to use FFmpeg as a IAudioSink?

**Comment by sipsorcery** [comment]
Do you need to get the audio to/from a real device? Can that even be done with Docker?

If you only need to generate audio then there are some classes that don't need a device that should work fine with docker. See:

 - [AudioSendOnlyMediaSession](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/app/Media/AudioSendOnlyMediaSession.cs)
 - [AudioExtrasSource](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/app/Media/Sources/AudioExtrasSource.cs)

**Comment by salihy** [comment]
It will just call a sip endpoint and play a voice file and hangup. It seems, this will work. Thanks I will try.

**Comment by vffuunnyy** [comment]
> It will just call a sip endpoint and play a voice file and hangup. It seems, this will work. Thanks I will try.

Greetings, [salihy](https://github.com/salihy) salihy. Can you tell me how you solved this problem?
I see that I need to pass `IMediaSession mediaSession` to the `Call` object, but `VoIPMediaSession` wants `MediaEndPoints`, which are not available in ffmpeg version, only in windows.

**Comment by salihy** [comment]
Hi @vffuunnyy, I don't remember and unfortuantely I don't have access to codebase anymore, sorry I can't help.

**Comment by vffuunnyy** [comment]
> Hi @vffuunnyy, I don't remember and unfortuantely I don't have access to codebase anymore, sorry I can't help.

Okay, thanks for the reply anyway.
I ended up doing it like this:

```csharp
var voipMediaSession = new VoIPMediaSession();
var callResult = await userAgent.Call(..., voipMediaSession, 15);

if (callResult)
{
    _audioMemoryStream.Position = 0;
    using (var audioStream = new MemoryStream(_audioMemoryStream.ToArray()))
    {
        Console.WriteLine("Sending audio stream.");
        await voipMediaSession.AudioExtrasSource.SendAudioFromStream(audioStream, AudioSamplingRatesEnum.Rate16KHz);
    }
    
    userAgent.Hangup();
}
```
