### ISSUE TITLE
Unable to load DLL 'avformat.58' in Ubuntu

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/SIPSorceryMedia.FFmpeg#31]
I have successfully execute my App in Windows BUT getting following errors in Ubuntu

Unhandled exception. System.DllNotFoundException: Unable to load DLL 'avformat.58 

Pls note that I have installed FFmpeg in Ubuntu: sudo apt install ffmpeg -y

**Comment by ChristopheI** [comment]
You have to install ffmpeg librairies not just ffmpeg executable.
Then you must specify the path to the librairies (the directory which contains avformat*, avutil*, etc ...)

When you start "ffmpeg --version" you have a full output of librairies available and also the directory path ;
Something like: **--libdir=--libdir=/usr/lib/aarch64-linux-gnu**

**Comment by ChristopheI** [comment]
Are you sure that you webcam is correctly set in you environment ?

Does ffmpeg executable itself can access to it ?

**Comment by ChristopheI** [comment]
With no answer difficult to help ...
