### ISSUE TITLE
frame dropped issue

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/SIPSorceryMedia.FFmpeg#32]
Getting followings:

01.
[dshow @ 0000023879ecb8c0] real-time buffer [HD Webcam] [video input] too full or near too full (98% of size: 3041280 [rtbufsize parameter])! frame dropped!
dshow passing through packet of type video size   296574 timestamp 19785225640000 orig timestamp 19785225629393 graph timestamp 19785225640000 diff 10607 HD Webcam

02.
[mjpeg @ 0000023879ed0b80] unable to decode APP fields: Invalid data found when processing input
Input #0, dshow, from 'video=HD Webcam':
  Duration: N/A, start: 1978522.165000, bitrate: N/A
  Stream #0:0: Video: mjpeg (Baseline), 1 reference frame (MJPG / 0x47504A4D), yuvj422p(pc, bt470bg/unknown/unknown, center), 1280x720, 30 fps, 30 tbr, 10000k tbn, 10000k tbc

Would you please help me to fix these issues.

**Comment by ChristopheI** [comment]
It's seems the same problem than https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg/issues/30

They are log entries directly coming from ffmpeg libraries not from [SIPSorceryMedia.FFmpeg](https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg) 

You should ask ffmpeg libraries comunity adn/or try with ffmpeg command line to reproduce the the pb.
