### ISSUE TITLE
Is it possible to convert SIPSorceryMedia.Abstractions.RawImage to System.Drawing.Image

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/SIPSorceryMedia.FFmpeg#39]
I need to convert SIPSorceryMedia.Abstractions.RawImage  to System.Drawing.Image to display image in a cross platform app developed in Avalonia.

**Comment by ChristopheI** [comment]
I'm sure other people in the community will be glad to know how you deal with that...

**Comment by mail2mhossain** [comment]
private void _videoSource_OnVideoSourceRawSampleFaster(uint durationMilliseconds, RawImage rawImage)
        {
            Bitmap bmpImage = new Bitmap(rawImage.Width, rawImage.Height, rawImage.Stride, PixelFormat.Format24bppRgb, rawImage.Sample);
        }
