### ISSUE TITLE
Is there any demo project that runs on Windows, MacOs and Linux.

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/SIPSorceryMedia.FFmpeg#40]
As per Documents, this project has been test successfully on Windows, MacOs and Linux.

Is there any demo project that runs on Windows, MacOs and Linux.

**Comment by ChristopheI** [comment]
These example are running on Windows, MacOs and Linux;
- https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg/tree/master/test/FFmpegConsoleApp
- https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg/tree/master/test/FFmpegFileAndDevicesTest
