### ISSUE TITLE
Feature Request: New event "OnVideoSourceAnyBitmapSampleFaster" like "OnVideoSourceRawSampleFaster"

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/SIPSorceryMedia.FFmpeg#48]
In OnVideoSourceRawSampleFaster event we get SIPSorceryMedia.Abstractions.RawImage.

requesting for a new event where we will get cross-platform IronSoftware.Drawing.AnyBitmap

**Comment by ChristopheI** [comment]
It will not be done. The Goal is to avoid the maximum number of dependencies.
You are using IronSoftware.Drawing.AnyBitmap.
Someone else could use SixLabor, another one SkiaShjarp etc ...
