### ISSUE TITLE
Is there any way to show SIPSorceryMedia.Abstractions.RawImage in a cross-platform (Win, Mac, Linux) App

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/SIPSorceryMedia.FFmpeg#52]
Is there any way to show SIPSorceryMedia.Abstractions.RawImage in a cross-platform (Win, Mac, Linux) App

**Comment by ChristopheI** [comment]
l already answered here: https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg/issues/47#issuecomment-1354346985
Please stop to ask same questions
