### ISSUE TITLE
Is there any way to quite from ffmpeg or clear the memory

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/SIPSorceryMedia.FFmpeg#55]
For SDL2 SDL2Helper.InitSDL() and SDL2Helper.QuitSDL() are available.

But for FFMPEG only FFmpegInit.Initialise() method is available.

Is there any way to quite from ffmpeg

**Comment by ha-ves** [comment]
As far as I know, you need to drop/unload the assembly then you will reclaim the memory, but in .NET this means you have to drop the entire app domain/context.

This will potentially need a complete overhaul of the current code to separate the loading of FFmpeg.AutoGen assemblies.

Another option is you'll have to run SIPSorceryMedia.FFmpeg in a separate process, and once you don't need it, terminate the process.

**Comment by ChristopheI** [comment]
This package uses [FFmpeg.AutoGen](https://github.com/Ruslan-B/FFmpeg.AutoGen) which doesn't seem to offer the option to do so.
Also I don't think there is a huge cost to have ffmpeg library "loaded" in term of memory/cpu.
