### ISSUE TITLE
Initialize: Method not supported

### ISSUE THREAD

**Issue by Gartarr** [sipsorcery-org/SIPSorceryMedia.FFmpeg#70]
When I try to initialize FFmpeg i get the following error:
```
System.NotSupportedException
  HResult=0x80131515
  Message=Specified method is not supported.
  Source=FFmpeg.AutoGen
  StackTrace:
   at FFmpeg.AutoGen.DynamicallyLoadedBindings.<>c.<Initialize>b__2_1244()
   at FFmpeg.AutoGen.DynamicallyLoadedBindings.<>c.<Initialize>b__2_525()
   at FFmpeg.AutoGen.ffmpeg.avdevice_register_all()
   at SIPSorceryMedia.FFmpeg.FFmpegInit.SetFFmpegBinariesPath(String path)
   at SIPSorceryMedia.FFmpeg.FFmpegInit.RegisterFFmpegBinaries(String libPath)
   at SIPSorceryMedia.FFmpeg.FFmpegInit.Initialise(Nullable`1 logLevel, String libPath, ILogger appLogger)
   at Frodo.Services.JanusClasses.RTCSession..ctor(Int32 missionId) in C:\FrodoNet\Services\WebRTC\RTCSession.cs:line 21
   at Frodo.Services.JanusClasses.JanusSession.<OnOfferReceived>d__47.MoveNext() in 

```

**Comment by ChristopheI** [comment]
You have to use FFmpeg 6 binaries - see https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg/commit/5b2dbe2dabef1131f214632346bde2ada9f8e229

**Comment by maaft** [comment]
I use ffmpeg 6.1 on ubuntu and still have the same isssue.

```c#
static void Main()
{
   FFmpegInit.Initialise(FfmpegLogLevelEnum.AV_LOG_FATAL, "/usr/bin/");
}
```

```
ffmpeg version 6.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
```

```
Unhandled exception. System.NotSupportedException: Specified method is not supported.
   at FFmpeg.AutoGen.DynamicallyLoadedBindings.<>c.<Initialize>b__2_1244()
   at FFmpeg.AutoGen.DynamicallyLoadedBindings.<>c.<Initialize>b__2_525()
   at FFmpeg.AutoGen.ffmpeg.avdevice_register_all()
   at SIPSorceryMedia.FFmpeg.FFmpegInit.SetFFmpegBinariesPath(String path)
   at SIPSorceryMedia.FFmpeg.FFmpegInit.RegisterFFmpegBinaries(String libPath)
   at SIPSorceryMedia.FFmpeg.FFmpegInit.Initialise(Nullable`1 logLevel, String libPath, ILogger appLogger)
   at demo.Program.Main() in /home/mawe/Downloads/WebRTCExamples/WebRTCGetStarted.Testing/Program.cs:line 46

```

**Comment by maaft** [comment]
never mind, aparrently the shared version has to be used.

@ChristopheI  please consider updating your readme for linux since ubuntu22.04 default ships with ffmpeg 4.

**Comment by hossam14102010** [comment]
@maaft did you find any solution for this issue I am having the same issue on windows

**Comment by richardtatum** [comment]
I am also having this issue on Arch Linux with FFMPEG installed to `/sbin` and accessible on the path.

**Comment by ChristopheI** [comment]
You must use
- ffmpeg 6.1.0 with shared libraries (eventually 6.1.1)
- launching "ffmpeg -version" must provide you the path where shared lib are stored.

Example of result on Linux:
`
root@linux-bot:/home/rolf/console2# ffmpeg -version
ffmpeg version 6.1.0 Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --disable-decoder=amrnb --disable-gnutls --disable-liblensfun --disable-libopencv --disable-podpages --disable-sndio --disable-stripping --enable-avfilter --enable-chromaprint --enable-frei0r --enable-gcrypt --enable-gpl --enable-ladspa --enable-libaom --enable-libaribb24 --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libdc1394 --enable-libdrm --enable-libdvdnav --enable-libdvdread --enable-libfdk-aac --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libiec61883 --enable-libilbc --enable-libjack --enable-libjxl --enable-libklvanc --enable-libkvazaar --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librabbitmq --enable-librist --enable-librsvg --enable-librubberband --enable-libshine --enable-libsmbclient --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-nonfree --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-openssl --enable-postproc --enable-pthreads --enable-shared --enable-version3 --incdir=/usr/include/x86_64-linux-gnu --libdir=/usr/lib/x86_64-linux-gnu --prefix=/usr --toolchain=hardened --enable-vaapi --enable-libvpl --enable-libxavs2 --enable-libdavs2 --enable-libvmaf --cc=x86_64-linux-gnu-gcc --cxx=x86_64-linux-gnu-g++ --disable-altivec --shlibdir=/usr/lib/x86_64-linux-gnu
`

So shared libraries are stored in /usr/lib/x86_64-linux-gnu

For windows, you can use this link to dwl them: https://github.com/GyanD/codexffmpeg/releases/download/6.1.1/ffmpeg-6.1.1-full_build-shared.zip
