### ISSUE TITLE
error: specified method not found 

### ISSUE THREAD

**Issue by jochennaumann** [sipsorcery-org/SIPSorceryMedia.FFmpeg#83]
I have tried version ffmpeg version 6.0, 6.1 and 7 full build in a simple .NET console app on windows 11:
```
using SIPSorceryMedia.FFmpeg;
FFmpegInit.Initialise();
```
and I am getting the same Exception
specified method not found
ffmpeg is in the path.
what am I doing wrong here?

_Originally posted by @hossam14102010 in https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg/issues/77#issuecomment-2239510505_

**Comment by hossam14102010** [comment]
first use version 6.0 and you can specify the path parameter in `FFmpegInit.Initialize()` method to where the ffmpeg is installed.

**Comment by jochennaumann** [comment]
I downloaded 6.0 full build ffmpeg with winget und changed the call to
    FFmpegInit.Initialise(FfmpegLogLevelEnum.AV_LOG_DEBUG, @"C:\Users\strelen\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-6.0-full_build\bin");

still the same error message: Specified method is not supported

**Comment by hossam14102010** [comment]
you should use the shared version, it ends with full_build-shared. to install it write in the cmd winget install `"FFmpeg (Shared)" -v 6.0`

**Comment by jochennaumann** [comment]
I tried the shared version, but the ffmpeg exe does not work on my windows 11 machine. When I try ffmpeg it just returns without any output. So I guess there are some dll wrong or missing. That's why I used the full build.

**Comment by hossam14102010** [comment]
how did you try it please reinstall the shared version and tell me how you used it, I think I had a similar issue.

**Comment by ha-ves** [comment]
> I tried the shared version, but the ffmpeg exe does not work on my windows 11 machine. When I try ffmpeg it just returns without any output. So I guess there are some dll wrong or missing. That's why I used the full build.

The full build doesn't include shared libraries that other apps can use.

Try using the one from here:
https://github.com/GyanD/codexffmpeg/releases/tag/6.1.1

Sometimes windows apps with shared libraries don't work well.

**Comment by jochennaumann** [comment]
I already tried the 6.1 full build version, it works with windows but gives
me the error in sip sorcery.
Anyways, I switched to Python for my project, they have the aiortc library
which works out of the box. Thanks for any help

Haves Irfan ***@***.***> schrieb am Sa., 14. Sept. 2024,
04:13:
