### ISSUE TITLE
Embed FFmpeg binaries in the package

### ISSUE THREAD

**Issue by hossam14102010** [sipsorcery-org/SIPSorceryMedia.FFmpeg#84]
there is a lot of issues about registering FFmpeg binaries. why not to embed it in the package?
recently, I had an issue with installing the binaries on my machine and it took me days to solve it.

**Comment by ChristopheI** [comment]
To target Windows it's easy.
But on Linux and Mac is totally different.
According the distribution/version you could need  specific binaries. 

If we start to add binaries, it will be a no end to manage all of them (Linux and Mac )
And also it's also necessary to check each of them.

There is also a lot of problem with "invalid" third-party (virus, ransomware, ...) especially binaries. So it's up to everyone to get the version they want.
