### ISSUE TITLE
Add Android support

### ISSUE THREAD

**Issue by hossam14102010** [sipsorcery-org/SIPSorceryMedia.FFmpeg#85]
if FFmpeg can work for android why not to add support for android?

**Comment by hossam14102010** [comment]
According to this [https://github.com/Ruslan-B/FFmpeg.AutoGen/issues/260](issue) we can't use FFmpeg.AutoGen with android. but we can use FFmpeg.AuroGen.Bindings.DynamicallyLoaded and FFmpeg.AutoGen.Abstractions. I tried to clone this repository and change to use these package with the ffmpeg libraries from [https://github.com/arthenica/ffmpeg-kit/tree/main/android](ffmpeg-kit). and I could initialize the library on android emulator, but the problem is I can't get the path of the camera to use it in the FFmpegCameraSource. I think we have to use the camera_index to specify the camera, but I don't know how to do so

**Comment by hossam14102010** [comment]
@ChristopheI, @sipsorcery can you give any help here?

**Comment by sipsorcery** [comment]
@hossam14102010 I have zero experience with Android so can't offer any advice.

**Comment by hossam14102010** [comment]
@sipsorcery I think to solve this issue all we need to know is how to open input device by index the issue occurs at this line: https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg/blob/917350fa67be090a2e2cbd862337e81c17306d80/src/FFmpegVideoDecoder.cs#L91
the avformat_open_input method returns -6 which I think it refers to device not found or invalid argument

**Comment by hossam14102010** [comment]
@sipsorcery I could use the `FFmpegFileSource` on Android. the problem is in using `FFmpegCameraSource`. also, I did not try but I think FFmpeg does not have support for audio capture on android so we cannot use the `FFmpegMicrophoneSource`, for this I think we have to use SDL2

**Comment by hossam14102010** [comment]
@sipsorcery when I try to use `FFmpegCameraSource` I get this in the logs:
```
[0:]
[android_camera @ 0x86d23280] No camera with index 0 available.

[0:]
[android_camera @ 0x86d23280] Failed to open camera.
[0:]
[android_camera @ 0x86d23280] Failed to open android_camera.
```

**Comment by hossam14102010** [comment]
the problem is I was testing on an old device with API 24 that FFmpeg does not support it. it worked successfully when I used it on a device with a higher API.

**Comment by hossam14102010** [comment]
I will make a pull request soon.
